SELECT p.NAME, SUM(w.SALARY * EXTRACT(EPOCH FROM (p.FINISH_DATE - p.START_DATE))/2628000) AS PRICE
FROM project p
JOIN project_worker pw ON p.ID = pw.PROJECT_ID
JOIN worker w ON pw.WORKER_ID = w.ID
GROUP BY p.NAME, w.SALARY
ORDER BY PRICE DESC;
